network_params:
  input_channel: 1
  output_channel: 256
  hidden_size: 256
imgH: 600
lang_list:
         - 'ru'
character_list: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюяЂђЃѓЄєІіЇїЈјЉљЊњЋћЌќЎўЏџҐґҒғҚқҮүҲҳҶҷӀӏӢӣӨөӮӯ!\"#$%&'()*+,-./:;<=>?[\\]_`{|}~ €₽0123456789
